# Creating an OLS function in Python

## Linear Algebra in _numpy_

We reviewed chapter 7 to understand how to generate an inverse matrix.

To transform matrix $X$ into $X^{-1}$. To do so, we must transform $[XI]$ into $[IX^{-1}]$. This is accomplished in chapter 7 of the text book. We are going to check the result using _numpy_.

In [3]:
#invertMatrix.py
import numpy as np
# create array to be transformed into vectors
x1 = np.array([1,2,1])
x2 = np.array([4,1,5])
x3 = np.array([6,8,6])
print("Array 1:", x1, sep="\n")
print("Array 2:", x2, sep="\n")
print("Array 3:", x3, sep="\n")

Array 1:
[1 2 1]
Array 2:
[4 1 5]
Array 3:
[6 8 6]


In [6]:
x1 = np.matrix(x1)
x2 = np.matrix(x2)
x3 = np.matrix(x3)
print("Vector 1", x1, sep = "\n")
print("Vector 2", x2, sep = "\n")
print("Vector 3", x3, sep = "\n")

Vector 1
[[1 2 1]]
Vector 2
[[4 1 5]]
Vector 3
[[6 8 6]]


Join x1, x2, and x3 using _np.concatenate()_. We define _axis = 0_ so that the rows are stacked vertically, not  horizontally.

In [9]:
X = np.concatenate((x1, x2, x3), axis = 0)
print("X:", X, sep = "\n")

X:
[[1 2 1]
 [4 1 5]
 [6 8 6]]


Now that we have defined our $X$ matrix, we can generate $X^{-1}$ by using _X.getI()_

In [11]:
X_inverse = X.getI()
print("X Inverse:", X_inverse, sep = "\n")

X Inverse:
[[-8.50000000e+00 -1.00000000e+00  2.25000000e+00]
 [ 1.50000000e+00  5.12410627e-17 -2.50000000e-01]
 [ 6.50000000e+00  1.00000000e+00 -1.75000000e+00]]


Next, use _np.round()_ to clearly present variables that include digits to the nth place (17).

In [13]:
X_inverse = np.round(X.getI(), 2)
print("X Inverse:", X_inverse, sep = "\n")

X Inverse:
[[-8.5  -1.    2.25]
 [ 1.5   0.   -0.25]
 [ 6.5   1.   -1.75]]


Finally, we should also see how to generate the transpose of a matrix. The transpose switches the index values $i$ and $j$. In otherwords, switch the row indexes with the column indexes.

In [17]:
print("X:", X, sep = "\n")
X_transpose = X.getT()
print("X Transpose:", X_transpose, sep = "\n")

X:
[[1 2 1]
 [4 1 5]
 [6 8 6]]
X Transpose:
[[1 4 6]
 [2 1 8]
 [1 5 6]]


## Diversion on Classes in Python

Create a sample class that contains math functions.

In [44]:
class Arithmetic:
    def __init__(self):
        #self.name = "arithmetic"
        pass
    def add(self, *args):
        total = 0
        try:
            for arg in args:
                total += arg
                
            return total
        except:
            ("pass list or tuple of ints or floats to add()")
    def multiply(self, *args):
        product = 1
        try:
            for arg in args: 
                product *= arg
            return product
        except:
            print("pass only int or float to multiply")
        

In [47]:
arithmetic = Arithmetic
print(arithmetic)
print(arithmetic.add(1,2,3,4))
print(arithmetic.multiply(1,2,3,4))
print(arithmetic.__dict__)

<class '__main__.Arithmetic'>
9
24
{'__module__': '__main__', '__init__': <function Arithmetic.__init__ at 0x0000026BBFAC6048>, 'add': <function Arithmetic.add at 0x0000026BBFAC6318>, 'multiply': <function Arithmetic.multiply at 0x0000026BBFAC64C8>, '__dict__': <attribute '__dict__' of 'Arithmetic' objects>, '__weakref__': <attribute '__weakref__' of 'Arithmetic' objects>, '__doc__': None}


## Building an OLS Regression Function

$\beta = (X'X)^{-1}X'Y$

An OLS regression posits a relationship between a dependent variable, $Y$, and independent variables - each $x_i$ - contained in $X$.

In [18]:
#econFreedomRegression.py
import pandas as pd

data = pd.read_csv("cleanedEconFreedomData.csv", 
    index_col = "Country Name")
data

World Rank  Region Rank  2017 Score  Property Rights  \
Country Name                                                                   
Afghanistan                  163.0         40.0   48.885716        12.600000   
Albania                       65.0         30.0   64.353003        54.013250   
Algeria                      172.0         14.0   46.528581        38.200000   
Angola                       165.0         41.0   48.515521        36.400000   
Argentina                    156.0         26.0   50.409088        32.449712   
Armenia                       33.0         19.0   70.306017        55.466155   
Australia                      5.0          4.0   81.015797        81.713325   
Austria                       30.0         17.0   72.265759        86.021044   
Azerbaijan                    68.0         15.0   63.599004        50.450592   
Bahamas                       90.0         19.0   61.081741        45.300000   
Bahrain                       44.0          4.0   68.472391        64.186382   
Bangladesh                   128.0         28.0   54.981640        34.880078   
Barbados                     130.0         24.0   54.501504        55.500000   
Belarus                      104.0         40.0   58.588849        50.900000   
Belgium                       49.0         25.0   67.846954        83.330042   
Belize                       101.0         22.0   58.629195        43.500000   
Benin                         96.0         11.0   59.237728        35.967527   
Bhutan                       107.0         21.0   58.445013        60.100000   
Bolivia                      168.0         30.0   47.696458        25.708213   
Bosnia and Herzegovina        92.0         36.0   60.221983        41.207063   
Botswana                      34.0          2.0   70.109960        58.093397   
Brazil                       140.0         25.0   52.853198        55.027146   
Bulgaria                      47.0         23.0   67.855456        62.535740   
Burkina Faso                  93.0         10.0   59.610196        38.200000   
Burma                        146.0         34.0   52.483818        22.992852   
Burundi                      139.0         30.0   53.189931        25.726852   
Cambodia                      94.0         20.0   59.518220        42.357595   
Cameroon                     150.0         34.0   51.811193        43.472263   
Canada                         7.0          1.0   78.507499        88.343914   
Cabo Verde                   116.0         17.0   56.949831        42.580891   
...                            ...          ...         ...              ...   
Spain                         69.0         31.0   63.572419        71.233022   
Sri Lanka                    112.0         25.0   57.394371        48.025916   
Sudan                        164.0         40.0   48.775526        31.100000   
Suriname                     167.0         29.0   48.026936        45.100000   
Swaziland                     88.0          8.0   61.134937        53.503082   
Sweden                        19.0         10.0   74.913207        88.561090   
Switzerland                    4.0          1.0   81.452148        86.930101   
Taiwan                        11.0          5.0   76.506760        86.494273   
Tajikistan                   109.0         23.0   58.167324        45.456005   
Tanzania                     105.0         14.0   58.584720        33.787585   
Thailand                      55.0         13.0   66.220285        51.250800   
Togo                         138.0         29.0   53.238028        33.800000   
Tonga                         73.0         17.0   63.010861        65.500000   
Trinidad and Tobago           87.0         18.0   61.228271        54.737088   
Tunisia                      123.0         10.0   55.713272        49.555006   
Turkey                        60.0         29.0   65.230960        61.256490   
Turkmenistan                 170.0         41.0   47.365115        32.400000   
Uganda                  